theme: jekyll-theme-midnight
title: Matt's homepage
description: My name is Matthew Hartman, I attended the University of Minnesota
  from 2019 to 2024. My majors are in Computer Science and the Studies of
  Cinema/Media Culture. My focus in computer science was in simulation models
  and 
